### ISSUE TITLE
Delete jpg and webp

### ISSUE THREAD

**Issue by aristotheme** [MRFD/kirby-webp#3]
Hii

for example upload img-001.jpg file and the plugin convert it to img-001.webp
but If I delete this img-001.jpg from panel.  deleted only img-001.jpg. It should be delete both file format?
.webp and .jpg

**Comment by MRFD** [comment]
Hi @aristotheme, I tried to reproduce it, without success. 

When I upload image-01.jpg via the Panel, the WebP variant is generated. Then when I delete image-01.jpg, the WebP variant is also deleted. Including the corresponding template files.

(This is a desired action, because WebP always needs a fallback format for old browsers).

**Comment by aristotheme** [comment]
Then nevermind :)
