### ISSUE TITLE
About $field->srcsetWebp()

### ISSUE THREAD

**Issue by aristotheme** [MRFD/kirby-webp#4]
Hi!

When I use this code 

    <div style="background-image: url('<?= $image->backgroundImage() ?>')"></div>

It works perfectly. I get webp image in Chrome and jpeg in Safari automatically.

But when I use this code

    <img src="<?= $image->url() ?>" srcset="<?= $image->srcset([300, 800, 1024]) ?>" />

I get only jpeg format both of the browser. Anything idea? or Did I get it all wrong?

Regards

**Comment by MRFD** [comment]
Hi @aristotheme , thanks for your message. Unfortunately there is an error in the documentation. On closer inspection, I have removed the part in question, because in my opinion it is duplicate. You can use `srcset` in two ways. I prefer to use the WebP field method:

```php
<?php
if ($image = $page->image('my-image.jpg')) {
    // Note the sizes array in the webp method.
    echo $image->webp('some-class', 'Image description', [300, 800, 1024]);
}
?>
```

It is also possible to do it the way you specify. You have to use the non-documented `webpObject` field method:

```php
<?php if ($image = $page->image('my-image.jpg')) : ?>
    <img src="<?= $image->webpObject()->url() ?>" srcset="<?= $image->srcsetWebp([300, 800, 1024]) ?>" />
<?php endif ?>
```

Hopefully this will solve your problem.

**Comment by aristotheme** [comment]
thank you so much i really appreciate
